ARG NODE_VERSION=18
ARG CLIENT_PORT=3001

FROM node:$NODE_VERSION-buster as base

WORKDIR /app

FROM base as builder

COPY package.json yarn.lock ./
RUN yarn install --frozen-lockfile

COPY . .

RUN yarn lerna bootstrap

FROM nginx:latest as production
WORKDIR /app

EXPOSE $CLIENT_PORT
CMD [ "npm", "run", "dev" ]
